name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Welcome"
          echo "Bye"
      # - name: Print greeting
      #   run: echo "Welcome to Github Actions"
      # - name: Print goodbye
      #   run: echo "Bye!! see you soon"
      
